In [4]:
import pandas as pd
df=pd.read_csv(r"D:\download\Sample-Spreadsheet-100-rows.csv")
df

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
0,01M015,P.S. 015 ROBERTO CLEMENTE,91,100,NaN,4.10,4.19,4.02,NaN,4.18,3.96
1,01M019,P.S. 019 ASHER LEVY,100,93,NaN,4.53,4.51,4.80,NaN,4.66,3.76
2,01M020,P.S. 020 ANNA SILVER,58,90,NaN,2.71,2.98,1.92,NaN,3.84,3.14
3,01M034,P.S. 034 FRANKLIN D. ROOSEVELT,29,100,95.0,2.69,2.59,2.14,NaN,3.67,2.38
4,01M063,THE STAR ACADEMY - P.S.63,80,100,NaN,NaN,NaN,NaN,NaN,NaN,3.77
...,...,...,...,...,...,...,...,...,...,...,...
1824,84X703,BRONX PREPARATORY CHARTER SCHOOL,57,95,79.0,3.50,3.08,3.51,NaN,2.93,2.76
1825,84X704,KIPP ACADEMY CHARTER SCHOOL,24,46,65.0,3.01,2.56,3.84,NaN,3.91,3.17
1826,84X706,HARRIET TUBMAN CHARTER SCHOOL,82,87,87.0,4.25,4.17,4.11,NaN,4.18,3.96
1827,84X718,BRONX CHARTER SCHOOL FOR BETTER LEARNING,88,84,NaN,4.10,4.25,4.27,NaN,4.64,4.23
1828,84X730,BRONX CHARTER SCHOOL FOR THE ARTS,68,91,52.0,2.37,2.25,2.56,NaN,4.00,3.19

In [2]:
df.isnull()

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
0,False,False,False,False,True,False,False,False,True,False,False
1,False,False,False,False,True,False,False,False,True,False,False
2,False,False,False,False,True,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,True,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...
1824,False,False,False,False,False,False,False,False,True,False,False
1825,False,False,False,False,False,False,False,False,True,False,False
1826,False,False,False,False,False,False,False,False,True,False,False
1827,False,False,False,False,True,False,False,False,True,False,False
1828,False,False,False,False,False,False,False,False,True,False,False

In [35]:
df.fillna(0)

Empty DataFrame
Columns: [DBN, School Name, Total Parent
Response Rate %, Total Teacher Response Rate %, Total Student Response Rate %, Collaborative Teachers Score, Effective School Leadership Score, Rigorous Instruction Score, Supportive Environment Score, Strong Family-Community Ties Score, Trust Score]
Index: []

In [4]:
df.isnull().sum().sum()

3452

In [5]:
df.shape

(1829, 11)

In [21]:
df.fillna(0)

Empty DataFrame
Columns: [DBN, School Name, Total Parent
Response Rate %, Total Teacher Response Rate %, Total Student Response Rate %, Collaborative Teachers Score, Effective School Leadership Score, Rigorous Instruction Score, Supportive Environment Score, Strong Family-Community Ties Score, Trust Score]
Index: []

In [45]:
df.fillna(method='ffill', axis = 1)

Empty DataFrame
Columns: [DBN, School Name, Total Parent
Response Rate %, Total Teacher Response Rate %, Total Student Response Rate %, Collaborative Teachers Score, Effective School Leadership Score, Rigorous Instruction Score, Supportive Environment Score, Strong Family-Community Ties Score, Trust Score]
Index: []

In [36]:
df.dropna(inplace = True)

In [39]:
df.ffill(inplace= True)

In [47]:
df['Total Parent \nResponse Rate %'].fillna(value=df['Total Parent \nResponse Rate %'].mean())

Series([], Name: Total Parent \nResponse Rate %, dtype: int64)

In [1]:
import pandas as pd
df=pd.read_csv(r"D:\download\Sample-Spreadsheet-100-rows.csv")
df
df.head()

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
0,01M015,P.S. 015 ROBERTO CLEMENTE,91,100,NaN,4.10,4.19,4.02,NaN,4.18,3.96
1,01M019,P.S. 019 ASHER LEVY,100,93,NaN,4.53,4.51,4.80,NaN,4.66,3.76
2,01M020,P.S. 020 ANNA SILVER,58,90,NaN,2.71,2.98,1.92,NaN,3.84,3.14
3,01M034,P.S. 034 FRANKLIN D. ROOSEVELT,29,100,95.0,2.69,2.59,2.14,NaN,3.67,2.38
4,01M063,THE STAR ACADEMY - P.S.63,80,100,NaN,NaN,NaN,NaN,NaN,NaN,3.77

In [2]:
df.loc[1]

DBN                                                01M019
School Name                           P.S. 019 ASHER LEVY
Total Parent \nResponse Rate %                        100
Total Teacher Response Rate %                          93
Total Student Response Rate %                         NaN
Collaborative Teachers Score                         4.53
Effective School Leadership Score                    4.51
Rigorous Instruction Score                            4.8
Supportive Environment Score                          NaN
Strong Family-Community Ties Score                   4.66
Trust Score                                          3.76
Name: 1, dtype: object

In [3]:
df.loc[5]

DBN                                                  01M064
School Name                           P.S. 064 ROBERT SIMON
Total Parent \nResponse Rate %                           52
Total Teacher Response Rate %                            96
Total Student Response Rate %                           NaN
Collaborative Teachers Score                           4.56
Effective School Leadership Score                      4.09
Rigorous Instruction Score                             3.74
Supportive Environment Score                            NaN
Strong Family-Community Ties Score                     4.18
Trust Score                                            4.04
Name: 5, dtype: object

In [4]:
df.loc[[5,6,7,8]]

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
5,01M064,P.S. 064 ROBERT SIMON,52,96,NaN,4.56,4.09,3.74,NaN,4.18,4.04
6,01M110,P.S. 110 FLORENCE NIGHTINGALE,79,77,NaN,3.11,3.15,1.96,NaN,3.67,3.29
7,01M134,P.S. 134 HENRIETTA SZOLD,46,93,NaN,2.51,1.53,3.19,NaN,3.38,2.55
8,01M140,P.S. 140 NATHAN STRAUS,57,89,87.0,3.44,4.21,3.40,NaN,3.59,3.70

In [5]:
df.loc[5,'Rigorous Instruction Score']

3.74

In [6]:
df.loc[5:15,'Rigorous Instruction Score']

5     3.74
6     1.96
7     3.19
8     3.40
9     3.23
10    2.77
11    3.85
12    3.30
13    3.81
14    2.70
15    3.75
Name: Rigorous Instruction Score, dtype: float64

In [7]:
df.loc[df['Rigorous Instruction Score']>2]

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
0,01M015,P.S. 015 ROBERTO CLEMENTE,91,100,NaN,4.10,4.19,4.02,NaN,4.18,3.96
1,01M019,P.S. 019 ASHER LEVY,100,93,NaN,4.53,4.51,4.80,NaN,4.66,3.76
3,01M034,P.S. 034 FRANKLIN D. ROOSEVELT,29,100,95.0,2.69,2.59,2.14,NaN,3.67,2.38
5,01M064,P.S. 064 ROBERT SIMON,52,96,NaN,4.56,4.09,3.74,NaN,4.18,4.04
7,01M134,P.S. 134 HENRIETTA SZOLD,46,93,NaN,2.51,1.53,3.19,NaN,3.38,2.55
...,...,...,...,...,...,...,...,...,...,...,...
1824,84X703,BRONX PREPARATORY CHARTER SCHOOL,57,95,79.0,3.50,3.08,3.51,NaN,2.93,2.76
1825,84X704,KIPP ACADEMY CHARTER SCHOOL,24,46,65.0,3.01,2.56,3.84,NaN,3.91,3.17
1826,84X706,HARRIET TUBMAN CHARTER SCHOOL,82,87,87.0,4.25,4.17,4.11,NaN,4.18,3.96
1827,84X718,BRONX CHARTER SCHOOL FOR BETTER LEARNING,88,84,NaN,4.10,4.25,4.27,NaN,4.64,4.23
1828,84X730,BRONX CHARTER SCHOOL FOR THE ARTS,68,91,52.0,2.37,2.25,2.56,NaN,4.00,3.19

# iloc()

In [12]:
df.iloc[0]

DBN                                                      01M015
School Name                           P.S. 015 ROBERTO CLEMENTE
Total Parent \nResponse Rate %                               91
Total Teacher Response Rate %                               100
Total Student Response Rate %                               NaN
Collaborative Teachers Score                                4.1
Effective School Leadership Score                          4.19
Rigorous Instruction Score                                 4.02
Supportive Environment Score                                NaN
Strong Family-Community Ties Score                         4.18
Trust Score                                                3.96
Name: 0, dtype: object

In [14]:
df.iloc[[0,1,2,3]]

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
0,01M015,P.S. 015 ROBERTO CLEMENTE,91,100,NaN,4.10,4.19,4.02,NaN,4.18,3.96
1,01M019,P.S. 019 ASHER LEVY,100,93,NaN,4.53,4.51,4.80,NaN,4.66,3.76
2,01M020,P.S. 020 ANNA SILVER,58,90,NaN,2.71,2.98,1.92,NaN,3.84,3.14
3,01M034,P.S. 034 FRANKLIN D. ROOSEVELT,29,100,95.0,2.69,2.59,2.14,NaN,3.67,2.38

In [15]:
df.iloc[:,0]

0       01M015
1       01M019
2       01M020
3       01M034
4       01M063
         ...
1824    84X703
1825    84X704
1826    84X706
1827    84X718
1828    84X730
Name: DBN, Length: 1829, dtype: object

In [18]:
df.iloc[0:5,1]

0         P.S. 015 ROBERTO CLEMENTE
1               P.S. 019 ASHER LEVY
2              P.S. 020 ANNA SILVER
3    P.S. 034 FRANKLIN D. ROOSEVELT
4         THE STAR ACADEMY - P.S.63
Name: School Name, dtype: object

In [19]:
df.iloc[0:5,1:4]

,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %
0,P.S. 015 ROBERTO CLEMENTE,91,100
1,P.S. 019 ASHER LEVY,100,93
2,P.S. 020 ANNA SILVER,58,90
3,P.S. 034 FRANKLIN D. ROOSEVELT,29,100
4,THE STAR ACADEMY - P.S.63,80,100

In [6]:
df.drop_duplicates()

,DBN,School Name,Total Parent \nResponse Rate %,Total Teacher Response Rate %,Total Student Response Rate %,Collaborative Teachers Score,Effective School Leadership Score,Rigorous Instruction Score,Supportive Environment Score,Strong Family-Community Ties Score,Trust Score
0,01M015,P.S. 015 ROBERTO CLEMENTE,91,100,NaN,4.10,4.19,4.02,NaN,4.18,3.96
1,01M019,P.S. 019 ASHER LEVY,100,93,NaN,4.53,4.51,4.80,NaN,4.66,3.76
2,01M020,P.S. 020 ANNA SILVER,58,90,NaN,2.71,2.98,1.92,NaN,3.84,3.14
3,01M034,P.S. 034 FRANKLIN D. ROOSEVELT,29,100,95.0,2.69,2.59,2.14,NaN,3.67,2.38
4,01M063,THE STAR ACADEMY - P.S.63,80,100,NaN,NaN,NaN,NaN,NaN,NaN,3.77
...,...,...,...,...,...,...,...,...,...,...,...
1824,84X703,BRONX PREPARATORY CHARTER SCHOOL,57,95,79.0,3.50,3.08,3.51,NaN,2.93,2.76
1825,84X704,KIPP ACADEMY CHARTER SCHOOL,24,46,65.0,3.01,2.56,3.84,NaN,3.91,3.17
1826,84X706,HARRIET TUBMAN CHARTER SCHOOL,82,87,87.0,4.25,4.17,4.11,NaN,4.18,3.96
1827,84X718,BRONX CHARTER SCHOOL FOR BETTER LEARNING,88,84,NaN,4.10,4.25,4.27,NaN,4.64,4.23
1828,84X730,BRONX CHARTER SCHOOL FOR THE ARTS,68,91,52.0,2.37,2.25,2.56,NaN,4.00,3.19